# Generated by Django 3.0 on 2019-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('autor', models.CharField(max_length=25)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
